sudo: false
language: node_js
node_js:
- 'lts/*'
env:
  global:
  - secure: T3+Dpcvgon48OnJsab2HWTJ3oPW7yp2cheVq6V/RoXYWYsFqgJsj5jnty270k0M4YLJPjPDzaVML1h/oHrY2fc0h+oEcHMG/N9l6enltEthFJJqjklDZ0wLcfRlAnOXdg8I43N8W7kUYWP1NvNpYmg4cu4YVeta9F8kPs6j/G2ET2HdAATBqLSBwv9I0L/RZhJw2vgQd7BemCLvRVGDfHuAxdcCWnZg0QQgF9Ek7soXLztqgYujV1Q0VY0sSd+Zn4Nh56hv5QWCOWX2qXuQUDln52iL4TvGX/Po0hs+fhyOQvF1rrInWBcx9fAoa9lzj6PWmWR2WhJllnPmQmjOfHm60qj+PB3SjxSQ36t/Obc2XqoLWZtjsIsrenQ8kWUrt3VvthnpuYotkgG9Snhszho7gXkR0ULLwAJWbKITHCaGXXjWS7OYc8fP9JkZS2wCNkAXenPRkvoWlI6j8zdRXu1uj2fXGv33U1FbrW4ooc024nfWFw6FlFDmBrguZwjBVH6Q2aoHGDyZmmkvRcmhAWc3UaYnuSEPtaBfYaoN1GjLTTaBxzPdkNUwby0vvPR36f9IQ01Z7b/GQiMelrQ92n7QEMss/8MmKoMn2bMrchp7jr+n7dFF0IPml//W3LKApNXfqqIsCTGC/pEzZ6ZXCZZ7y3Xv6raA9gIic/DnbZuw=
after_success:
# update gh-page only for master
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
